vuepress/awesome-vuepress

- README.md
添加了 EasyHexo 和 D2-daily 这两个项目。
> Add EasyHexo and D2-daily

- README.md
update: picgo-core, thanks for your work!
> update: picgo-core

- README.md
- Merge [meteorlxy/awesome-vuepress](https://github.com/meteorlxy/awesome-vuepress)
- Sort official plugins in alphabetical order
> merge meteorlxy/awesome-vuepress

- README.md
Added MTGJSON link to open-source projects.
> add: mtgjson

- README.md
Update the official plugin urls to point to v1 website
> Fix broken urls

- README.md
> feat: add vuepress-plugin-serve

- README.md
今天的新插件~
一个不太优雅的补丁，暂时没有想到更好的做法所以先以插件的形式发布，供大家参考~
> feat: plugin-ssr-mismatch-workaround

- README.md
> Update clean-urls plugin link in README.md

- README.md
Hi!  
This blog post outline an approach to adding VuePress into an existing project (Vue component library) and providing live component examples and source code documentation for each component in the plugin.
> Blog post-`Using VuePress for component library documentation`

- README.md
> add vuesion/vuesion to OSS projects using vuepress

- README.md
- [Mevn-CLI](https://mevn.madhacks.co)
- [teachcode](https://teachcode.madhacks.co)
> Added Mevn-CLI and teachcode to the list

- README.md
I've wrote some tutorials for building blog with Vuepress on GitLab Pages with SSL setup.
- [20190320 Create a Blog with VuePress on GitLab Pages](https://blog.howar31.com/vuepress-blog-tutorial/)
- [20190625 Secure GitLab Pages with Let's Encrypt Certificate](https://blog.howar31.com/lets-encrypt-ssl-gitlab-pages)
> Add tutorials by Howar31

- README.md
> feat: add vuepress-theme-thindark.

- README.md
> feat: add vuepress-plugin-global-toc

- README.md
add theme `vuepress-theme-default-prefers-color-scheme`
> add: vuepress-theme-default-prefers-color-scheme

- README.md
Thought this should belong External Resources as it's official documentation from the Ghost crew 😃 👻 
Link added: https://ghost.org/docs/api/v2/vuepress/
> Add Working with Ghost and VuePress

- README.md
add plugin vuepress-plugin-gitalk-maker
> add: vuepress-plugin-gitalk-maker

- README.md
Add kriry开发者网络 open source  site powered by  Vuepress
> Add kriry开发者网络 open source  powered by  Vuepress

- README.md
// cc @recoluan @newsbielt703
Very good theme, by contrast, the default blog theme feels a little ashamed.
> feat: add vuepress-theme-reco

- README.md
A colorful and simple blog theme
https://iwenson.com
> feat: add vuepress-theme-seeker

- README.md
A VuePress theme that supports a dark theme, multiple color themes, and other useful features. A live demo can be seen at https://discordjs.guide/
> Add vuepress-theme-yuu to the Community Themes list

- README.md
[Java 全栈知识体系](https://www.pdai.tech/)
> Added open source documentation website that use VuePress.

- README.md
Add user authorization with [v-dialogs](https://github.com/TerryZ/v-dialogs) (login form in Modal) in VuePress.
> Add example for authorization

- README.md
add vuepress-theme-ting ::frog: :cactus:小清新风格-A simple and fresh style of vuepress theme.
> add vuepress-theme-ting

- README.md
> feat: add a blog using Vuepress

- README.md
Modify preview address
把原地址替换为稳定的地址
> vuepress-theme-ting主题修改预览地址

- README.md
feature: add vuepress-plugin-element-ui
> feat: add vuepress-plugin-element-ui

- README.md
AzureSelected is a site use vuepress engine.
> Suggest site use vuepress: AzureSelected

- README.md
Hi guys! I've prepared another vuepress plugin.
> Add vuepress-plugin-smartlook

- README.md
Plug-ins that gray your site for VuePress.(Generally used for Mourning Day)
> add vuepress-plugin-graysite plugin.

- README.md
Add @kawarimidoll/vuepress-plugin-tailwind to the end of Community Plugins list.
> Add @kawarimidoll/vuepress-plugin-tailwind

- README.md
Added my `vuepress-theme-solarized` to the `Themes` section :)
> docs: add vuepress-theme-solarized

- README.md
> feat: add vuepress-theme-hope

- README.md
Add my theme to a list of community themes.
> feat: add vuepress-theme-material-free

- README.md
Add the vuepress-theme-carbon and 2 of my projects where I use - and love using - vuepress.
> Add Carbon theme and 2 Open Source projects

- README.md
Baidu statistical analysis plugin for vuepress    &  vuepress-plugin-toolbar
> add vuepress-plugin-baidu-tongji-analytics & toolbar

- README.md
A simple and efficient VuePress knowledge management & blog theme. 知识管理&博客 主题。
> Add vuepress-theme-vdoing

- README.md
> Add vuepress-theme-note

- README.md
2 columns VuePress blog theme built with Vuetify.
Demo: https://vuepress-theme-blog-vuetify.ttskch.com/
Repo: https://github.com/ttskch/vuepress-theme-blog-vuetify/
> feat: add vuepress-theme-blog-vuetify

- README.md
These are websites that use the VuePress framework to create handbooks for the Pinewood Builders community
> Added example websites

- README.md
Forgot to add this in originally
> Added deployed platform for blog site

- README.md
Hello @ulivz,
I've written a plugin to add the web-monetization header to VuePress sites. Would be awesome to list it as well. Let me known if you got any questions.
Cheers,
Peter
> feat: add web-monetization plugin

- README.md
ADD
```md
- [vuepress-theme-mustom](https://github.com/jinyaoMa/vuepress-theme-mustom) - Simple design theme for VuePress - [PREVIEW](https://jinyaoMa.github.io/vuepress-theme-mustom)
```
to `### Community Themes`
AND
```md
- [Mark's Personal Website](https://jinyaoMa.github.io/vuepress-theme-mustom)
```
to `### Blogging`
> feat: add vuepress-theme-mustom

- README.md
Add vuepress-plugin-lastest-version into awesome vuepress.
> feat: add vuepress-plugin-lastest-version

- README.md
Hey @ulivz and @cyrilf 
I've built a little plugin to allow using privacy-friendly [Umami Analytics](https://github.com/mikecao/umami) for VuePress:
<https://github.com/spekulatius/vuepress-plugin-umami>
Would be great if we could add it in 💪️
Peter
> Adding Umami compontent

- README.md
Added a new tutorial how I created our new multi-language marketing site using Vuepress, TailwindCSS. 
It covers the following topics:
- Creating a custom theme
- Creating custom components
- Internationalization (i18n)
- Search-engine-optimization (SEO)
- Migration from Wordpress
- Cookie Management / Consent / GDPR
- Structured Data (JSON-LD)
> docs: add new tutorial

- README.md
✔️ No conflicts
✔️ Added to end of list
> docs: add @adamdehaven/vuepress-plugin-custom-tooltip

- README.md
A theme developed based on VuePress
> docs: add @qcyblm/vuepress-theme-vpx

- README.md
Add plugin,theme and Open Source
> docs: add plugins, theme and open source

- README.md
> docs: add vuepress-plugin-qrcode

- README.md
This plugin allow to display all child page of the current page
> docs: add vuepress-plugin-child-toc

- README.md
Add VuePress Plugin for Facebook Pixel
> docs: add vuepress-plugin-facebook-pixel

- README.md
Hey,
I've built a VuePress plugin to connect to [Ackee](https://github.com/electerious/Ackee). Maybe this could be added?
Cheers,
Peter
> Adding vuepress-plugin-ackee

- README.md
Added 1980's Maker to Blogging Websites
> docs: add 1980's Maker blog

- README.md
🐉 A flat and clean Blog Theme for VuePress site, inspired by Hexo-theme-inside.
> docs: add vuepress-theme-maker

- README.md
Adding my blog [christofer.rocks](https://christofer.rocks)
> docs: add Reflections to blogging section

- README.md
A page for VuePress Theme gallery, keep update.
> docs: add a vuepress theme gallery

- README.md
Added vuepress-plugin-vue-example
> Added vuepress-plugin-vue-example

- README.md
Added the JavaScript library I maintain, http://two.js.org/, because it's site now uses VuePress! Thank you Vue.js & VuePress team!
> New Documentation Project Added

- README.md
The vuepress-plugin-archive plugin can provide archive and timeline functions for the vuepress site
> docs: add vuepress-plugin-archive plugin

- v1.md
add buxianshan's Blog in v1.md
> docs: add buxianshan's Blog

- v2.md
home: https://www.qbenben.com/docs/play/vuepress-plugin-clipboard.html
npm: https://www.npmjs.com/package/vuepress-plugin-clipboard
github: https://github.com/Zhengqbbb/zhengqbbb.github.io/tree/main/packages/clipboard
home: https://www.qbenben.com/docs/play/vuepress-plugin-china-search-console.html
npm: https://www.npmjs.com/package/vuepress-plugin-china-search-console
github: https://github.com/Zhengqbbb/zhengqbbb.github.io/tree/main/packages/china-search-console
home: https://v2-vuepress-theme-gungnir.vercel.app/
docs: https://v2-vuepress-theme-gungnir.vercel.app/docs/basic/intro.html
github: https://github.com/Renovamen/vuepress-theme-gungnir
home: http://cz-git.qbenben.com/
npm: https://www.npmjs.com/package/cz-git
github: https://github.com/Zhengqbbb/cz-git
> docs: add plugin. open source. theme. blog

- v2.md
Add vuepress-theme-mix in `v2.md`
> docs: add community themes for v2

- v1.md
> 🎚 An immersive and personalized vuepress music plugin
[English] | [简体中文](https://github.com/simonzhangs/vuepress-plugin-immersive-music-player#readme)
- Support custom configuration to play playlist
- Support for custom configuration playback progress bar theme
- 🌟 new! Support the user interface to directly input the playlist ID to replace the playlist. Blog visitors can enter the selected playlist when browsing the blog
```bash
$ yarn add vuepress-plugin-immersive-music-player
```
- `npm run build`,when the dist folder is generated after construction, the plug-in takes effect and can be deployed to your own server.
- 🍖 Personalized playback progress bar
- 👗 Global player component
- 🍒 Based on NetEase Cloud Interface
- 🔧 Easy to configure
```bash
$ yarn add …
```
> docs: add vuepress-plugin-immersive-music-player

- v2.md
a vuepress 2 plugin to basis support for netlify functions when you want deploy to netlify and use netlify functions.
> docs: add  vuepress-plugin-netlify-funtions

- v2.md
vuepress-plugin-china-search-console: https://vuepress.qbb.sh/china-search-console/
vuepress-plugin-clipboard: https://vuepress.qbb.sh/clipboard/
blog:
- https://blog.qbb.sh/
- https://blog.zxh.io/
> docs: update link

- v2.md
A VuePress v2 plugin,It is used to generate the right navigation directory anchor!
> Add a new Plugin

- v2.md
- Removes a broken link: [Knzn's Blog](https://www.knzn.net/). It seems to be no longer live.
- Adds a new link in Blogging: [NdagiStanley's web profile](https://md.engineer/).
> Removes broken link and add a new link in Blogging

- v2.md
Update `vuepress-theme-plume` Links to new site, update description.
> update `vuepress-theme-plume` link and desc.
